Drewbott/Campshare

assets/javascript/share.js

share page takes in user input and stores into database

inputs in form and stores into database

---

assets/javascript/login.js

i updated the login.js file please pull it up <3

initial login.js

---

assets/javascript/login.js

added area for login variables

updated login.js

---

assets/css/style.css
index.html

Added those cards back in, took out jumbotron image

redid index.html layout

---

assets/css/style.css
index.html

Added a link and changed some style

added link to login.html

---

assets/css/style.css
index.html

changed the container and div layout to the Welcome section and the jumbotron. Still working it out so they line up next to each other, but making progress.

style changes to the homepage

---

assets/css/style.css

stylized jumbotron and cards

---

index.html

fixed navbar and javascript call issues

fixed navbar issues w/ index.html

---

assets/javascript/share.js

After submitting the share form, the data will be pushed up to the user's id in firebase

postings now attach to a user's id in firebase

---

assets/css/style.css
find.html

I added the styling to the cards to include map and weather data. footer needs help still.

added card style

---

assets/css/style.css
find.html

coded out a responsive, sticky footer...

sticky footer

---

assets/javascript/index.js
assets/javascript/login.js
index.html

index.html -------------------
- changed href to src when linking index.js
- removed the linked slim version of jquery on bottom of page (that one doesn't have $.get in its library)
- added profileButton id to log in button so it shows display name if logged in
index.js ---------------------
- added quotes to href when targeting attr of profileButton
- deleted some console logs
login.js ------------------------
- deleted commented out functions that weren't being used
- changed db to database to keep things consistent on every page
- ToS url and privacy url are placeholder url now

log in is working again!

---

assets/javascript/share.js
share.html

share.html ---------------
- added firebase link to head
- added profileButton id to log in button
- changed href="index.js" to src="share.js" at the bottom of the body
- changed id's for the start date and end date to startDate and endDate respectively
share.js ---------------------
- changed db to database for consistency across files
- removed var date and separated to startDate and endDate
- changed notes to requirements

share page uploads to firebase

---

assets/javascript/find.js
assets/javascript/share.js

share.js ------------------
- changed path in data base to "posts/" instead of "users/userID"
- after clicking submit button on share page leads to profile.html(temporarily)
- userId is now stored in database of the post
find.js -----------------
- added console log that can pull a key (i.e location) but it pulls all locations

changed database ref path to 'posts/' instead of users/userId

---

assets/javascript/find.js

added ajax call and console log to find.js to connect to NPS api

console for national park shows name

---

assets/javascript/find.js
assets/javascript/maps.js
find.html

maps.js
-created a Source of truth object and maps recenter function for yosemite
find
-function call that will correlate park code in event call to show map for that park

recenter maps function with parkcode from event listener

---

assets/javascript/maps.js

maps.js
-updated lat long for all parkcodes

updated maps object

---

assets/javascript/login.js

deleted line that refreshes page if logged out

fixed log in page refresh

---

assets/javascript/maps.js

maps.js
-removed extra marker from initial map
- all markers up to date!

updated initial map to show markers and remove redundant marker

---

assets/javascript/find.js
assets/javascript/index.js
assets/javascript/share.js
find.html
index.html
share.html

- added log out button. hidden when not logged in and shows when logged in
- removed href from some buttons and used jquery to redirect to another page depending on if theyre logged in or not.

log in required when sharing. log out button added

---

assets/javascript/find.js
index.html

find container dynamically appends the divs again

fixed now will display listings
